import { Product } from '@models/Product';

export const defaultProducts: Product[] = [{
  productId: 0,
  name: 'Paraguas Verde',
  active: true,
  price: 400.0,
  categoryId: 2,
  photo: '',
  discount: 0,
  freeShipping: false,
  stock: 200,
},
{
  productId: 0,
  name: 'Paraguas Rojo',
  active: true,
  price: 420.0,
  categoryId: 2,
  photo: '',
  discount: 0,
  freeShipping: true,
  stock: 200,
},
{
  productId: 0,
  name: 'Paraguas Azul',
  active: true,
  price: 820.0,
  categoryId: 2,
  photo: '',
  discount: 50,
  freeShipping: false,
  stock: 200,
},
{
  productId: 0,
  name: 'Paraguas de Bokita',
  active: true,
  price: 1500.0,
  categoryId: 2,
  photo: '',
  discount: 80,
  freeShipping: true,
  stock: 160,
},
]